[project]
name = "nbodyPackage"
version = "0.0.1"
dependencies = [
   "numpy","scipy","matplotlib",
]
authors = [
  { name="Will Martin", email="wamartin@syr.edu" },{ name="Jada Garofalo", email="jagarofa@syr.edu" },
]
description = "An n-body simulation for PHY607 project 2"
readme = "README.txt"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
example_script = "nbodyPackage:main"
